#server
server:
  port: 10000

#JDBC
#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@//localhost:1521/XE
#    username: hr
#    password: 1234


# mybatis
spring:
  ssl:
    enabled: true # aws https 배포 설정
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//localhost:1521/XE
      username: hr
      password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: "true" # 쿠키 사용 허용

api:
  service-key: "SKv4XWbYnhPIp8DiMdTGGW4BJA%2B1P8%2FnOxUcw1kC5Spm8Y1RA5Afctm5dQMI29z1MtPtcXkIT1lZ%2F5saInc42w%3D%3D"

  base-url: "https://apis.data.go.kr/B551011/KorPetTourService2"
  area-based-list: "/areaBasedList2"

  base-url2: "https://api.odcloud.kr/api"
  uddi:9c79ebd1: "/15071311/v1/uddi:9c79ebd1-20e1-4e97-8e6a-b65e890fbe85"
